# -*- coding: utf-8 -*-
"""Deal ledger rows (working first pass). Fields follow the extraction
instruction's section 11.2 layout. Quotes are checked against the filing text
by build_workbook.py."""

# quote shorthands (exact filing text; verified by the builder)
Q = {
"partyA": "During the meeting, Party A suggested possible joint venture arrangements and expressed some interest in acquiring equity in the Company to further develop strategic opportunities and enhance regional connectivity.",
"subcom": "the Board appointed a subcommittee of two independent directors, Frank W. Barrett and Richard W. Anderson, to interview potential investment bankers to represent the Company in possible negotiations with Party A and to assist the Board in evaluating additional strategic options for the realization of shareholder value, including potential change in control transactions.",
"ghf1": "the subcommittee recommended to the Board that the Company retain GHF as its investment banking firm.",
"ghf2": "Following this presentation, the Board approved the subcommittee’s recommendation and the Company engaged GHF.",
"ghf3": "GHF represented to the Company that it would not represent any potential buyer of the Company in connection with an offer to purchase the Company or any person proposing to provide financing in connection with such an offer.",
"m14": "the Board considered various factors, including the marketplace, the risks attendant to engaging in the process discussed with representatives of GHF, the Company’s overall strategic position, and the challenges attendant to improving the Company’s financial performance in order to maximize shareholder value and concluded, based upon its examination of these and other factors, that it was in the best interest of the Company",
"m14b": "and its shareholders to proceed with the transaction strategy discussed with representatives of GHF.",
"tc": "the Board appointed a special committee of independent directors of the Board (which we refer to as the “Transaction Committee”), composed of Frank W. Barrett (Chair), Richard W. Anderson and James C. Garvey, for the purpose of assisting in the supervision and oversight of the process on the full Board’s behalf and making a recommendation to the full Board.",
"m3223": "Mr. Noreck reported that he and other members of the senior management team had met with various representatives of Party A on March 22 and 23, 2016 and had informed Party A of GHF’s engagement.",
"auth": "The Transaction Committee authorized GHF to contact Party A as well as other potential buyers to determine their level of interest in a change in control transaction.",
"wave": "During the week of March 28, 2016, in accordance with the Transaction Committee’s directives, representatives of GHF contacted 11 potential strategic buyers (including Party A) and 18 potential financial buyers.",
"nda": "Each of the potential strategic buyers and 14 potential financial buyers subsequently executed confidentiality agreements.",
"nostand": "The confidentiality agreements did not contain any “standstill” or similar provision that would prohibit a potential buyer from submitting a proposal or making an offer to acquire the Company.",
"classI": "Mr. Noreck reported that the Company had also approached two additional Class I railroads to determine their interest in a possible transaction.",
"conv": "Between April 3, 2016 and April 6, 2016, representatives of GHF and members of the Company’s management held a series of introductory meetings with five potential strategic buyers (including G&W) at the American Short Line and Regional Railroad Association’s 2016 Connections Convention (“2016 Connections Convention”).",
"apr7": "the Transaction Committee authorized representatives of GHF, on behalf of the Company, to contact each of the five interested parties with whom management had met at the 2016 Connections Convention, as well as other potential strategic buyers (including certain Class I railroads) and private equity firms who had entered into confidentiality agreements with the Company to confirm their continuing interest.",
"partyB": "Subsequently, on April 21, 2016, the Company and representatives of GHF held an introductory meeting with another potential strategic buyer (“Party B”).",
"memo": "a memorandum concerning the Company and its prospects, which was distributed to the potential buyers, including Party A, Party B and G&W, that had executed confidentiality agreements.",
"deadline": "each potential buyer had been advised to submit a non-binding indication of interest by May 10, 2016 (which deadline was subsequently postponed to May 19, 2016 to ensure the potential buyers had sufficient time to formulate their most compelling offers).",
"iois": "Between May 19, 2016 and June 1, 2016, the Company received nine written indications of interest (“IOIs”) from potential buyers, with offer prices per share ranging from $17.93 to $26.50 (assuming the conversion of preferred stock into common stock), implying equity values of $90 million to $134 million.",
"twolow": "In view of the substantial amount of management time that would be required for management presentations, the Transaction Committee concluded that the two low bidders should be excluded from that process.",
"seven": "The Transaction Committee authorized representatives of GHF to schedule in-person management presentations with the remaining seven potential buyers and allow these parties to conduct additional due diligence. These potential buyers were given access to an internet data site to conduct legal and financial due diligence.",
"loi": "In mid-June 2016, at the direction of the Transaction Committee, representatives of GHF instructed all potential buyers to submit non-binding letters of intent (“LOIs”) by July 20, 2016, together with mark-ups of the forms of merger agreement, disclosure letter and voting agreement, which GHF indicated would be posted to the internet data site.",
"loi2": "Potential buyers were instructed to provide a valuation for the Company based on the purchase of 100% of the outstanding common stock on a dollar per share basis (assuming conversion of the preferred stock into common stock) or the financial terms of any non-cash proposal.",
"drafts": "On June 29, 2016, the Company posted an initial draft of merger agreement to the internet data site, and on June 30, 2016, the Company posted an initial draft of voting agreement with respect to the common stock and preferred stock held by the Eder Trusts. On July 11, 2016, the Company posted an initial draft of disclosure letter to the internet data site.",
"partyC": "In early July 2016, a potential strategic buyer that had not previously been part of the process (“Party C”) approached the Company’s management and expressed interest in acquiring the Company.",
"partyCnda": "After executing a confidentiality agreement, Party C was provided the memorandum concerning the Company provided to the other potential buyers.",
"partyCioi": "On July 12, 2016, Party C submitted an IOI with an offer price per share of $21.00 (implying an equity value of $108 million).",
"partyCpres": "Subsequently, Party C was provided access to the internet data site and the Company’s management held a management presentation with Party C by telephone on July 14, 2016.",
"lois": "In late July 2016, the Company received six LOIs with offer prices per share ranging from $19.20 to $24.00 (implying equity values of $96 million to $121 million). Party B, G&W and another bidder (“Party D”) also provided mark-ups of the draft merger agreement and voting agreement. One bidder (“Party E”) provided a summary of material issues and proposed changes to the merger agreement and voting agreement with respect to those issues.",
"b": "Party B submitted an LOI to acquire the Company for a price of $24.00 per share (subject to an expedited diligence review).",
"gw1": "G&W submitted an LOI on July 21, 2016 to acquire the Company for a price of $21.15 per share (subject to a three-week exclusive diligence period). The price included $20.02 cash at closing and $1.13 in the form of a contingent value right, the value of which was based on the subsequent sale of the Company’s South Quay property (“CVR”).",
"gw2": "On July 26, 2016, in response to feedback from representatives of GHF indicating its price and CVR structure were not competitive, G&W submitted a revised LOI, which increased its offer to $22.15 per share (including $21.02 in cash and $1.13 CVR).",
"e": "Party E (a strategic buyer) submitted an LOI to acquire the Company for a price of $21.26 per share (subject to a 60-day exclusivity period for due diligence and negotiation of definitive documentation).",
"d": "Party D (a financial buyer) submitted an LOI to acquire the Company for a price of $21.00 per share (subject to a four-week diligence period).",
"c": "Party C submitted an LOI to acquire the Company for a price of $19.30 per share (subject to a 30-day diligence period).",
"f": "Party F (a strategic buyer) submitted an LOI to acquire the Company for a price of $19.20 per share (subject to a 30-day due diligence period).",
"assump": "In addition to various due diligence requirements, the LOI prices were based on different assumptions and requirements related to transaction expenses and change in control payments, which GHF and the Transaction Committee observed could affect the ultimate offer price.",
"elect": "One strategic buyer and one financial buyer elected not to submit an LOI.",
"sel": "The Transaction Committee concluded that the Company should proceed with confirmatory due diligence and negotiations with G&W and Party B because of the higher offers made by each of G&W and Party B relative to the other potential buyers. At the direction of the Transaction Committee, representatives of GHF subsequently contacted the remaining bidders to inform them that they were no longer involved in the process.",
"calls": "On July 29, 2016, representatives of GHF had calls with Party D and Party E. During those calls, Party D and Party E both expressed interest in reengaging and enhancing their offers.",
"rev": "On August 1, 2016, Party D submitted a revised LOI at a price of $24.00 per share and Party E submitted a revised LOI, along with financing support, from Party F, at a price of $23.81 per share. Both revised proposals contained a 30-day due diligence period.",
"dout": "Party D declined to shorten its due diligence period and requested that the Company commit that it would not enter into an agreement with another bidder during its 30-day due diligence period. In light of the active interest of Party B and G&W, the Company declined to make such a commitment, at which point Party D indicated that it would not proceed with further due diligence at that time.",
"ewd": "Party E withdrew its revised proposal on August 2, 2016 (but confirmed its original proposal of $21.26 per share)",
"prior": "the Transaction Committee directed the management team and representatives of each of BMO and Hinckley Allen to continue diligence and negotiations with both G&W and Party B, but given the higher price offered by Party B, to prioritize Party B and proceed to complete the negotiation of the merger agreement with Party B.",
"onsite": "From July 27, 2016 through August 11, 2016, Party B and G&W conducted on-site financial, legal and environmental due diligence, including hi-rail trips to inspect the Company’s track infrastructure.",
"baug4": "On August 4, 2016, legal counsel for Party B provided a revised draft of the merger agreement and, following negotiations between their respective legal counsels, the Company provided Party B with a revised draft of the merger agreement and disclosure letter on August 5, 2016.",
"gwsept": "Following that discussion, the Transaction Committee directed representatives of BMO to inform G&W that the Company intended to enter into a merger agreement with another bidder. G&W requested that it be allowed to continue its due diligence, including physical due diligence on August 10 and August 11, 2016, to potentially facilitate an improved offer, which request was granted.",
"simpson": "On August 10, 2016, representatives of Hinckley Allen and Simpson Thacher & Bartlett LLP (which we refer to as “Simpson Thacher”), G&W’s legal counsel, discussed various provisions of the draft merger agreement and voting agreement that had been provided to G&W on August 3, 2016, and Hinckley Allen provided Simpson Thacher with a revised disclosure letter to accompany the August 3 draft merger agreement.",
"gwsignal": "On August 11, 2016, G&W indicated its possible intention to submit a revised LOI on August 12, 2016, having just completed its physical diligence of the Company’s track infrastructure.",
"gw25": "G&W submitted a revised LOI to acquire the Company for a price of $25.00 per share in cash, which excluded the previously proposed CVR, together with mark-ups of the merger agreement and the voting agreement. G&W’s LOI further indicated that the offer would expire at 6:00 p.m. on the following day.",
"bdecline": "At the request of the Board, representatives of BMO then contacted Party B to determine if it would increase its offer price. Party B indicated that it would not increase its price.",
"superior": "The Board determined that the G&W offer represented the superior proposal.",
"exec": "Shortly thereafter, Hinckley Allen and Simpson Thacher finalized the transaction documents and the Company and G&W executed the merger agreement, and the Company, G&W and the Eder Trusts executed the voting agreement.",
"ann": "The Company issued a press release publicly announcing the transaction on Monday, August 15, 2016 prior to the opening of trading of the Company’s common stock on the NASDAQ.",
"ha": "Members of management and representatives of each of GHF and the Company’s legal counsel, Hinckley, Allen & Snyder LLP (which we refer to as “Hinckley Allen”), participated in all meetings of the Transaction Committee, except as otherwise indicated.",
"stb": "The Board arranged a telephone call with the Company’s STB counsel to discuss the process for obtaining the required regulatory approval or exemption for the transaction, the risks associated with each process, the use of a voting trust to enable an earlier closing of the transaction (as contemplated by the G&W merger agreement) and the likely timeframe for obtaining any regulatory clearance for a transaction with either Party B or G&W.",
"fee": "the Company will pay BMO an aggregate fee of approximately $2.52 million, a portion of which was paid upon the signing of GHF’s engagement letter with the Company and in three monthly installments thereafter, a portion of which was paid upon delivery of BMO’s opinion, and the remainder and majority of which is payable upon consummation of the merger.",
"conflict": "a BMO affiliate has a participation in G&W’s existing secured syndicated debt facility as described under the section titled “Summary of Financial Analysis of BMO Capital Markets Corp.—Miscellaneous” on page 41. On September 6, 2016, the Board considered this new information, determined this relationship was not material to BMO’s independence and confirmed that the Board remained comfortable with the engagement and opinion of BMO.",
"gwx": "the termination fee payable by the Company in the event the Board exercised its “fiduciary out” in order to accept a superior proposal was less under the G&W draft agreement than the Party B draft agreement",
"opinion": "BMO then rendered an oral opinion to the Board, subsequently confirmed by delivery of a written opinion, dated August 12, 2016 to the effect that, as of that date, and based upon and subject to the various assumptions made, procedures followed, matters considered and qualifications and limitations on the scope of review undertaken by BMO as set forth in its written opinion, the merger consideration to be received by the holders of our common stock in the merger pursuant to the merger agreement was fair, from a financial point of view, to those holders (other than the Eder Trusts).",
"retain": "We retained GHF, the business of which was subsequently acquired by BMO, an affiliate of Bank of Montreal, to act as our financial advisor in connection with the merger.",
"sq": "BMO included the book value of $12.5 million of the Company’s South Quay property to each of the three valuation methodologies.",
"25": "25 of whom entered into confidentiality agreements with the Company and received information related to the Company and six of whom submitted non-binding letters of intent",
"premium": "the value of the merger consideration of $25.00 per share in cash represents a 53% premium over the per share closing price of the Company’s common stock of $16.30 on August 12, 2016, the last trading day concluded prior to the Company and G&W entering into the merger agreement",
"nofin": "the absence of a financing condition in the merger agreement and the representation of G&W in the merger agreement as to its financial wherewithal",
"fee3785": "payment of a termination fee of $3.785 million to G&W",
}


def R(**kw):
    d = dict(
        rowid="", n=None, when="", who="", what="", process=1, rnd="", type="",
        terms="", formality="", cond="", why="", source=[], review="",
        count=None, dfrom=None, dto=None, wdate=None, dbasis="", dmethod="",
        plow=None, phigh=None, pkind="", porigin="", currency="",
        allcash="", cashclose=None, cdetail="", duedate=None, dtreat="",
        rfinal="", decided="", exit="", obasis="", page=None, related="",
        include="Yes")
    d.update(kw)
    return d


ROWS = [
R(rowid="R001", n=1, when="Fourth quarter 2015 (day not disclosed)",
  who="Party A (Class I rail partner)",
  what="Bidder interest", rnd="0", type="Strategic",
  terms="Unpriced, inbound expression of interest: Party A suggested possible joint ventures and expressed interest in acquiring equity in PWRR. Not a bid; direction inbound from a commercial partner.",
  why="Stated: “" + Q["partyA"] + "” (p.27). Convention: this is a preliminary, unpriced interest, not an acquisition proposal; recorded as the first-contact fact for Party A. Working date is the Q4 2015 calendar midpoint (Assigned: midpoint) as a display convention (Q7).",
  source=["P-002"], review="Q7", count=1,
  dfrom="2015-10-01", dto="2015-12-31", wdate="2015-11-15",
  dbasis="Approximate window", dmethod="Assigned: midpoint", page=27),

R(rowid="R002", n=2, when="Fourth quarter 2015 (after Party A's expression of interest; day not disclosed)",
  who="PWRR Board (subcommittee of Barrett and Anderson)",
  what="Target decision", rnd="0",
  terms="Board appointed a two-director subcommittee to interview investment banks and evaluate strategic options, including potential change-of-control transactions, prompted by Party A's interest. Sale exploration, not a commitment to sell.",
  why="Stated: “" + Q["subcom"] + "” (p.27). Inferred: the appointment followed receipt of a report of the Party A meeting; timing is only Q4 2015. Working date shares the Q4 2015 midpoint with R001; their order within the quarter is not disclosed (Q7).",
  source=["P-002"], review="Q7",
  dfrom="2015-10-01", dto="2015-12-31", wdate="2015-11-15",
  dbasis="Approximate window", dmethod="Assigned: midpoint", page=27),

R(rowid="R003", n=3, when="01/27/2016", who="PWRR / GHF (later BMO)",
  what="Adviser engaged", rnd="0",
  terms="Board approved retaining Greene Holcomb & Fisher LLC (GHF) as the Company's investment banking firm after the subcommittee interviewed several firms; GHF represented it would not represent any potential buyer or financing provider. GHF's business was acquired by BMO Capital Markets Corp. on 08/01/2016; the relationship continues as BMO (fee approx. $2.52 million, majority payable at closing).",
  why="Stated: “" + Q["ghf1"] + "” and “" + Q["ghf2"] + "” (p.27). Stated: “" + Q["ghf3"] + "” (p.27). Adviser engaged — actual reported engagement. Later disclosures (fee, BMO acquisition, fairness opinion) sit on this same relationship; a renamed/acquired firm does not get a second adviser row.",
  source=["P-002", "X-016", "X-022"], count=None,
  dfrom="2016-01-27", dto="2016-01-27", wdate="2016-01-27",
  dbasis="Reported day", dmethod="Reported", page=27,
  related="adviser relationship continues as BMO (R056)"),

R(rowid="R004", n=4, when="03/14/2016", who="PWRR Board", what="Target sale decision", rnd="0",
  terms="Board approved GHF's proposed process: proceed with discussions with Party A and also solicit interest from other third parties regarding a change-in-control transaction. Transaction Committee appointed (Barrett (Chair), Anderson, Garvey) to supervise the process; the committee could not itself approve a transaction.",
  why="Stated: “" + Q["m14"] + "” and “" + Q["m14b"] + "” (pp.27-28) and “" + Q["tc"] + "” (p.28). Candidate Round 1 anchor kept as its own row: the outreach wave began about two weeks later and is used instead (Q1).",
  source=["P-003", "P-004"], review="Q1", count=None,
  dfrom="2016-03-14", dto="2016-03-14", wdate="2016-03-14",
  dbasis="Reported day", dmethod="Reported", page=27,
  related="candidate R1 anchor for R007"),

R(rowid="R005", n=5, when="03/24/2016", who="Transaction Committee / GHF", what="Target decision",
  rnd="0",
  terms="Committee authorized GHF to contact Party A and other potential buyers to gauge interest in a change-in-control transaction; management reported its 03/22-03/23 meetings with Party A and that Party A had been told of GHF's engagement.",
  why="Stated: “" + Q["m3223"] + "” and “" + Q["auth"] + "” (p.28). Candidate Round 1 anchor kept as its own row: it launched outreach within about a week, but the dated first outreach wave is the anchor (Q1).",
  source=["P-005", "P-006"], review="Q1", count=None,
  dfrom="2016-03-24", dto="2016-03-24", wdate="2016-03-24",
  dbasis="Reported day", dmethod="Reported", page=28,
  related="candidate R1 anchor for R007"),

R(rowid="R006", n=6, when="Participated in committee meetings from 03/24/2016 (service date; retention date not disclosed)",
  who="Hinckley, Allen & Snyder LLP (target legal counsel)",
  what="Adviser service observed", rnd="0",
  terms="Company legal counsel; participated in all Transaction Committee meetings from 03/24/2016; drafted and negotiated the merger agreement and disclosure letter, responded to bidder diligence questions, and advised the Board.",
  why="Stated: “" + Q["ha"] + "” (p.28). Adviser service observed, not engaged: the filing does not give a retention date, so the earliest supported service date (the 03/24/2016 committee meeting) is used. First narrative mention is not itself proof of retention.",
  source=["P-006", "P-025", "P-028"], count=None,
  dfrom="2016-03-24", dto="2016-03-24", wdate="2016-03-24",
  dbasis="Reported day", dmethod="Reported", page=28),

R(rowid="R007", n=7, when="Week of 03/28/2016", who="PWRR / GHF", what="Round opened", rnd="1",
  terms="R1 anchor: first outreach wave — GHF contacted 11 potential strategic buyers (including Party A) and 18 potential financial buyers during the week of 03/28/2016 to determine interest in a change-in-control transaction. Other candidate anchors: R005 (03/24/2016 committee authorization; direct launch within about a week) and R004 (03/14/2016 Board process decision). Objective: gauge interest and solicit non-binding indications of interest (IOI deadline later set for 05/10/2016, revised to 05/19/2016). Finality: Not final — an indicative, non-binding stage with no final or binding solicitation.",
  why="Stated: “" + Q["wave"] + "” (p.28). Convention: R1 opens with the first outreach wave under the section 6.3 rule; the engagement (R003) and the process decisions (R004, R005) were earlier. Not final: the filing announces no final or binding solicitation at this stage (Q1).",
  source=["P-006"], review="Q1", rfinal="Not final",
  dfrom="2016-03-28", dto="2016-04-03", wdate="2016-03-28",
  dbasis="Reported interval", dmethod="Assigned: bound", page=28,
  related="R004; R005; anchored on the wave; admits R008/R009 contacts"),

R(rowid="R008", n=8, when="Week of 03/28/2016", who="11 potential strategic buyers (incl. Party A)",
  what="Contact", rnd="1", type="Strategic",
  terms="Target-initiated outreach by GHF to determine interest in a change-in-control transaction; 11 strategic buyers contacted. Party A was already in contact since Q4 2015 (R001).",
  why="Stated: “" + Q["wave"] + "” (p.28). Inferred: these are whole-company acquisition contacts (acquisition of the Company, not a segment). Party A is counted once in this cohort though its first contact is R001 (contact detail row, Q3).",
  source=["P-006"], review="Q3", count=11,
  dfrom="2016-03-28", dto="2016-04-03", wdate="2016-03-28",
  dbasis="Reported interval", dmethod="Assigned: bound", page=28),

R(rowid="R009", n=9, when="Week of 03/28/2016", who="18 potential financial buyers",
  what="Contact", rnd="1", type="Financial",
  terms="Target-initiated outreach by GHF; 18 financial buyers (private equity/financial investors) contacted about a change-in-control transaction.",
  why="Stated: “" + Q["wave"] + "” (p.28). Cohort split by type as the filing supplies the split. Four of these 18 did not sign confidentiality agreements (R013).",
  source=["P-006"], review="Q3", count=18,
  dfrom="2016-03-28", dto="2016-04-03", wdate="2016-03-28",
  dbasis="Reported interval", dmethod="Assigned: bound", page=28),

R(rowid="R010", n=10, when="by 04/07/2016 (reported at the 04/07/2016 committee meeting; approach day not disclosed)",
  who="Two additional Class I railroads", what="Contact", rnd="1", type="Strategic",
  terms="The Company separately approached two additional Class I railroads to gauge transaction interest. Overlap with the 11 strategic buyers contacted by GHF is unresolved; additive Count left blank rather than assuming disjointness.",
  why="Stated: “" + Q["classI"] + "” (p.28). Inferred: the approaches preceded the 04/07/2016 report and followed the outreach decision; only the report date is supported. Working date = the known bound (Assigned: bound). Qualified quantity: contact total is 29 plus up to 2 unresolved (Q3).",
  source=["P-008"], review="Q3", count=None,
  dto="2016-04-07", wdate="2016-04-07",
  dbasis="Relative only", dmethod="Assigned: bound", page=28),

R(rowid="R011", n=11, when="04/07/2016", who="Transaction Committee / GHF", what="Target decision",
  rnd="1",
  terms="Committee authorized GHF to contact the five convention attendees (including G&W) and other strategic buyers and private equity firms under confidentiality agreement to confirm continuing interest; management had also approached two additional Class I railroads (R010).",
  why="Stated: “" + Q["apr7"] + "” (p.28). Process continuation, not a new round; the round's information stage (management presentations and data room) is uniform for advancing bidders (R020).",
  source=["P-008"], count=None,
  dfrom="2016-04-07", dto="2016-04-07", wdate="2016-04-07",
  dbasis="Reported day", dmethod="Reported", page=28),

R(rowid="R012", n=12, when="after week of 03/28/2016; by 04/22/2016 (execution days not disclosed)",
  who="11 strategic NDA signers", what="NDA signed", rnd="1", type="Strategic",
  terms="Each of the 11 strategic buyers contacted by GHF executed a confidentiality agreement; no standstill or similar provision. Party A, Party B and G&W are inside this cohort; their individual NDA dates are not disclosed. Party B's inclusion is assumed (R014 assumes otherwise for count purposes; Q3).",
  why="Stated: “" + Q["nda"] + "” (p.28) and “" + Q["nostand"] + "” (p.28). Inferred: agreements executed after the contact wave and exist by 04/22/2016, when the memorandum went to buyers that had executed them (R014). Working date = window midpoint (Q7).",
  source=["P-006", "P-009"], review="Q3", count=11,
  dfrom="2016-03-28", dto="2016-04-22", wdate="2016-04-09",
  dbasis="Approximate window", dmethod="Assigned: midpoint", page=28),

R(rowid="R013", n=13, when="after week of 03/28/2016; by 04/22/2016 (execution days not disclosed)",
  who="14 potential financial NDA signers", what="NDA signed", rnd="1", type="Financial",
  terms="14 of the 18 financial buyers contacted executed confidentiality agreements; no standstill. Four contacted financial buyers did not sign and are not counted as NDA participants. Party D is a financial buyer within this cohort.",
  why="Stated: “" + Q["nda"] + "” (p.28). Inferred: same window as R012. Cohort split by type as supplied (Q3).",
  source=["P-006"], review="Q3", count=14,
  dfrom="2016-03-28", dto="2016-04-22", wdate="2016-04-09",
  dbasis="Approximate window", dmethod="Assigned: midpoint", page=28),

R(rowid="R014", n=14, when="04/21/2016", who="Party B", what="Contact", rnd="1", type="Strategic",
  terms="Target-initiated introductory meeting between the Company/GHF and Party B, 'another potential strategic buyer'. Whether Party B is one of the 11 buyers contacted in the week of 03/28/2016 is not stated; additive Count left blank. Party B executed a confidentiality agreement by 04/22/2016.",
  why="Stated: “" + Q["partyB"] + "” (p.28). Stated: the 04/22/2016 memorandum went to buyers including Party B 'that had executed confidentiality agreements' (p.28). Count left blank because the overlap with R008 is unresolved (Q3).",
  source=["P-008", "P-009"], review="Q3", count=None,
  dfrom="2016-04-21", dto="2016-04-21", wdate="2016-04-21",
  dbasis="Reported day", dmethod="Reported", page=28),

R(rowid="R015", n=15, when="by 04/27/2016 (advice reported at the 04/27/2016 Board meeting)",
  who="PWRR Board / GHF", what="Deadline set", rnd="1",
  terms="All potential buyers advised to submit a non-binding indication of interest by 05/10/2016; communicated at or before the 04/27/2016 Board executive session (held without Mr. Eder). Due date: 05/10/2016.",
  why="Stated: “" + Q["deadline"] + "” (p.29). The advice is known only through the later report, so Working date = the report day as the known bound (Assigned: bound); the 05/10/2016 due date was later superseded (R016).",
  source=["P-010"], review="Q2", duedate="2016-05-10", dtreat="Extended",
  dto="2016-04-27", wdate="2016-04-27",
  dbasis="Relative only", dmethod="Assigned: bound", page=29),

R(rowid="R016", n=16, when="after 04/27/2016; before 05/19/2016 (revision day not disclosed)",
  who="PWRR / GHF", what="Deadline revised", rnd="1",
  terms="IOI deadline postponed from 05/10/2016 to 05/19/2016 to give buyers time to formulate their most compelling offers; target-side action, not a bidder request. New due date: 05/19/2016.",
  why="Stated: “" + Q["deadline"] + "” (p.29). Inferred: revision occurred after the 04/27/2016 report and before the replaced date; Working date = midpoint of that window (Assigned: midpoint, Q7).",
  source=["P-010"], review="Q2; Q7", duedate="2016-05-19",
  dfrom="2016-04-28", dto="2016-05-19", wdate="2016-05-08",
  dbasis="Relative only", dmethod="Assigned: midpoint", page=29),

R(rowid="R017", n=17, when="05/19/2016", who="PWRR / potential buyers", what="Deadline", rnd="1",
  terms="IOI due date reached. Deadline treatment: Enforced — after the due date the committee reviewed the IOIs (05/23/2016) and excluded the two low bidders (06/01/2016) on the bids in hand, with no revision to the due date. The receipt window 05/19-06/01 straddles the due date, so no late bid is recorded.",
  why="Stated: “" + Q["deadline"] + "” and “" + Q["iois"] + "” (p.29). Convention: treatment determined from what followed in the round (Enforced; no extension and no late-acceptance finding because the window straddles the date) (Q2).",
  source=["P-010", "P-011"], review="Q2", duedate="2016-05-19", dtreat="Enforced",
  dfrom="2016-05-19", dto="2016-05-19", wdate="2016-05-19",
  dbasis="Reported day", dmethod="Reported", page=29),

R(rowid="R018", n=18, when="Between 05/19/2016 and 06/01/2016",
  who="Nine IOI bidders (anonymous cohort)", what="Bid", rnd="1", type="Unknown",
  terms="Nine written non-binding IOIs from potential buyers; offer prices $17.93-$26.50 per share as-converted, implying equity values of $90-$134 million. Bid basis: purchase of 100% of outstanding common stock on a dollar-per-share basis assuming preferred conversion. Mixed strategic/financial population not split by the filing.",
  why="Stated: “" + Q["iois"] + "” (p.29). Formality: Informal (preliminary indications, no final/binding solicitation; no bidder-returned agreement markups reported). Conditions: Heavy by context — made before substantive (data-room or management) access; “" + Q["seven"] + "” shows data-site access came only after the 06/01/2016 selection. Group price envelope; not a per-member range (Q3, Q6).",
  source=["P-011", "P-012"], review="Q3; Q5; Q6", count=9,
  dfrom="2016-05-19", dto="2016-06-01", wdate="2016-05-19",
  dbasis="Reported interval", dmethod="Assigned: deadline",
  plow=17.93, phigh=26.50, pkind="Group envelope", porigin="Stated", currency="USD",
  allcash="Not stated", formality="Informal", cond="Heavy",
  cdetail="Fin: not stated; DD required: substantive; DD open: no; Excl: not stated", page=29),

R(rowid="R019", n=19, when="by 05/19/2016",
  who="16 remaining wave NDA signers (anonymous cohort)", what="Did not submit", rnd="1",
  type="Unknown",
  terms="Inferred: residual — 25 wave NDA signers (11 strategic + 14 financial) minus 9 IOI submitters = 16 non-submitters; base assumes all nine IOIs came from the 25 signers. No motive, date or identity is inferred for any member.",
  why="Inferred: arithmetic base — “" + Q["nda"] + "” (p.28) and “" + Q["iois"] + "” (p.29); the Reasons section states “" + Q["25"] + "” (p.33). Eligibility: all potential buyers were advised to submit IOIs (R015). Closing inference at the first identified transition (Q4).",
  source=["P-011", "P-006", "X-012"], review="Q3; Q4", count=16,
  dto="2016-05-19", wdate="2016-05-19",
  dbasis="Relative only", dmethod="Assigned: deadline", page=29,
  decided="Unknown", exit="Not stated", obasis="Inferred: residual"),

R(rowid="R020", n=20, when="06/01/2016", who="Transaction Committee", what="Round opened", rnd="2",
  terms="R2 opens: after committee review of the IOIs on 05/23/2016 and 06/01/2016, the committee excluded the two low bidders and selected the remaining seven to advance to in-person management presentations and additional diligence, with access to an internet data site. Uniform stage access for all advancing bidders; no differentiated access. Objective: presentations and diligence ahead of LOI submissions. Finality: Not final — no final, binding or best-and-final solicitation (the LOI deadline is set later, R023).",
  why="Stated: “" + Q["seven"] + "” and “" + Q["twolow"] + "” (p.29). Convention: a distinct information stage linked to the coming offers opens R2; an alternative boundary (the mid-June LOI instruction) is kept as R023 (Q1). The 05/23/2016 review is folded here; it did not decide anything.",
  source=["P-011"], review="Q1", rfinal="Not final",
  dfrom="2016-06-01", dto="2016-06-01", wdate="2016-06-01",
  dbasis="Reported day", dmethod="Reported", page=29,
  related="R021; R023; admits R029-R035"),

R(rowid="R021", n=21, when="06/01/2016", who="Two low IOI bidders (anonymous cohort)",
  what="Dropped by target", rnd="1", type="Unknown",
  terms="Excluded from the management-presentation stage: the two lowest of the nine IOIs. Stage left: Round 1 (advancement decision). Stated reason: lower offers than rivals.",
  why="Stated: “" + Q["twolow"] + "” (p.29). Exit reason Lower offer than rivals; identity of the two is not disclosed and is not inferred. Outcome basis Stated (no notice date is given; Working date = decision day).",
  source=["P-011"], count=2,
  dfrom="2016-06-01", dto="2016-06-01", wdate="2016-06-01",
  dbasis="Reported day", dmethod="Reported", page=29,
  decided="Target", exit="Lower offer than rivals", obasis="Stated"),

R(rowid="R022", n=22, when="by 06/01/2016", who="Party A", what="Did not submit", rnd="1",
  type="Strategic",
  terms="Inferred: identity — Party A last appears at the 04/22/2016 memorandum distribution to NDA signers and is not mentioned in the bidding rounds; recommended reading: it sits in the 16-signer non-submitter residual (R019). Alternative: it could be one of the two low bidders excluded on 06/01/2016 (R021). Count 0; no unit is moved from either cohort.",
  why="Inferred: “" + Q["memo"] + "” (p.28); non-submitter base per R019 arithmetic. The row records only that Party A was out by the 06/01/2016 transition, not how or why. Working date = the advancement decision (Assigned: decision day, Q4).",
  source=["P-009", "P-011"], review="Q4", count=0,
  dto="2016-06-01", wdate="2016-06-01",
  dbasis="Relative only", dmethod="Assigned: decision day", page=28,
  decided="Unknown", exit="Not stated", obasis="Inferred: identity"),

R(rowid="R023", n=23, when="Mid-June 2016", who="PWRR / GHF", what="Deadline set", rnd="2",
  terms="All potential buyers instructed to submit non-binding LOIs by 07/20/2016 with mark-ups of the forms of merger agreement, disclosure letter and voting agreement (posted to the data site 06/29, 06/30 and 07/11/2016); valuation instructed on a 100%-of-common dollar-per-share basis assuming preferred conversion, or non-cash terms. Due date: 07/20/2016.",
  why="Stated: “" + Q["loi"] + "” and “" + Q["loi2"] + "” (p.29) and “" + Q["drafts"] + "” (p.29). Draft postings are transaction documents, not separate ledger rows (section 4). In context 'all potential buyers' means the continuing participants (R020) plus late entrant Party C; Q3.",
  source=["P-012", "P-013"], review="Q2; Q3", duedate="2016-07-20", dtreat="Late bids accepted",
  dfrom="2016-06-11", dto="2016-06-20", wdate="2016-06-15",
  dbasis="Approximate window", dmethod="Assigned: midpoint", page=29,
  related="carries the R2 solicitation deadline (Q1 alternative boundary)"),

R(rowid="R024", n=24, when="Early July 2016 (day not disclosed)", who="Party C",
  what="Contact", rnd="2", type="Strategic",
  terms="Inbound: a potential strategic buyer not previously in the process approached management expressing interest in acquiring the Company. Bidder-initiated.",
  why="Stated: “" + Q["partyC"] + "” (p.29). Working date = midpoint of the early-July band (Assigned: midpoint; Q7).",
  source=["P-014"], review="Q7", count=1,
  dfrom="2016-07-01", dto="2016-07-10", wdate="2016-07-05",
  dbasis="Approximate window", dmethod="Assigned: midpoint", page=29),

R(rowid="R025", n=25, when="Early July 2016 (after approach; day not disclosed)", who="Party C",
  what="NDA signed", rnd="2", type="Strategic",
  terms="Late entrant Party C executed a confidentiality agreement; NDA count is additional to the 25 wave signers (total 26 executed bidder NDAs; the filing's '25' describes the wave group).",
  why="Stated: “" + Q["partyCnda"] + "” (p.29). Stated: Reasons states “" + Q["25"] + "” (p.33) — reconciliation in Summary and Q3.",
  source=["P-014", "X-012"], review="Q3", count=1,
  dfrom="2016-07-01", dto="2016-07-10", wdate="2016-07-05",
  dbasis="Approximate window", dmethod="Assigned: midpoint", page=29),

R(rowid="R026", n=26, when="Early July 2016 - 07/14/2016", who="Party C",
  what="Information access changed", rnd="2", type="Strategic",
  terms="Late entrant catch-up access: Party C was given the buyer memorandum already provided to wave signers, then internet data-site access, and a management presentation by telephone on 07/14/2016. Other live bidders had received these earlier, so this is differentiated catch-up access, not uniform stage access.",
  why="Stated: “" + Q["partyCnda"] + "” and “" + Q["partyCpres"] + "” (p.29). One row for the access decision. Working date moved to the nearest admissible day (07/05/2016) to keep sequence after R024/R025 while inside its early-July-07/14 window (Assigned: sequence; Q7).",
  source=["P-014"], review="Q3; Q7", count=None,
  dfrom="2016-07-01", dto="2016-07-14", wdate="2016-07-05",
  dbasis="Approximate window", dmethod="Assigned: sequence", page=29),

R(rowid="R027", n=27, when="07/12/2016", who="Party C", what="Bid", rnd="2", type="Strategic",
  terms="IOI at $21.00 per share (implied equity value $108 million), submitted before data-site access and the 07/14/2016 management presentation. Late entrant; informal indication ahead of its LOI (R032).",
  why="Stated: “" + Q["partyCioi"] + "” (p.29). Formality: Informal (preliminary indication; no formal signal). Conditions: Heavy by context — no substantive access before the bid; data-site access followed the bid (R026).",
  source=["P-014", "P-020"], review="Q5", count=1,
  dfrom="2016-07-12", dto="2016-07-12", wdate="2016-07-12",
  dbasis="Reported day", dmethod="Reported",
  plow=21.00, phigh=21.00, pkind="Point", porigin="Stated", currency="USD",
  allcash="Not stated", formality="Informal", cond="Heavy",
  cdetail="Fin: not stated; DD required: substantive; DD open: no; Excl: not stated", page=29),

R(rowid="R028", n=28, when="07/20/2016", who="PWRR / potential buyers", what="Deadline", rnd="2",
  terms="LOI due date reached. Deadline treatment: Late bids accepted — G&W's LOI arrived 07/21/2016 and was considered, and G&W revised it on 07/26/2016, without any deadline revision.",
  why="Stated: “" + Q["gw1"] + "” (p.29) with the due date from R023. Convention: a bid dated after the due date considered by the target supports late acceptance, not an extension (Q2).",
  source=["P-012", "P-017"], review="Q2", duedate="2016-07-20", dtreat="Late bids accepted",
  dfrom="2016-07-20", dto="2016-07-20", wdate="2016-07-20",
  dbasis="Reported day", dmethod="Reported", page=29),

R(rowid="R029", n=29, when="Late July 2016 (day not disclosed; before the 07/27/2016 selection)",
  who="Party B", what="Bid", rnd="2", type="Strategic",
  terms="LOI at $24.00 per share, subject to an expedited diligence review; submitted together with mark-ups of the draft merger agreement and voting agreement.",
  why="Stated: “" + Q["b"] + "” and “" + Q["lois"] + "” (p.29). Formality: Formal — bidder-returned acquisition agreement markups (signal 1). Conditions: Light — only an expedited/confirmatory diligence review; no financing or other condition reported. Received window 07/20-07/27 (Q7): the 07/27/2016 meeting is the first point by which all six LOIs are established as received; the 07/22/2016 review makes 07/20-07/22 the likelier window (not entered as a bound).",
  source=["P-015", "P-016"], review="Q5; Q7", count=1,
  dfrom="2016-07-20", dto="2016-07-27", wdate="2016-07-20",
  dbasis="Approximate window", dmethod="Assigned: deadline",
  plow=24.00, phigh=24.00, pkind="Point", porigin="Stated", currency="USD",
  allcash="Not stated", formality="Formal", cond="Light",
  cdetail="Fin: not stated; DD required: confirmatory; DD open: yes; Excl: not stated", page=29),

R(rowid="R030", n=30, when="Late July 2016 (day not disclosed; before the 07/27/2016 selection)",
  who="Party E", what="Bid", rnd="2", type="Strategic",
  terms="LOI at $21.26 per share, subject to a 60-day exclusivity period for due diligence and negotiation of definitive documentation; provided a summary of material issues and proposed changes to the merger agreement and voting agreement instead of full mark-ups.",
  why="Stated: “" + Q["e"] + "” and “" + Q["lois"] + "” (p.30). Formality: Informal — an issues summary is not a returned agreement markup; no other formal signal (borderline, Q5). Conditions: Heavy — stated multi-week exclusive diligence and definitive-document negotiation period.",
  source=["P-018", "P-015"], review="Q5; Q7", count=1,
  dfrom="2016-07-20", dto="2016-07-27", wdate="2016-07-20",
  dbasis="Approximate window", dmethod="Assigned: deadline",
  plow=21.26, phigh=21.26, pkind="Point", porigin="Stated", currency="USD",
  allcash="Not stated", formality="Informal", cond="Heavy",
  cdetail="Fin: not stated; DD required: substantive (60 days); DD open: yes; Excl: requested (60 days)", page=30),

R(rowid="R031", n=31, when="Late July 2016 (day not disclosed; before the 07/27/2016 selection)",
  who="Party D", what="Bid", rnd="2", type="Financial",
  terms="LOI at $21.00 per share, subject to a four-week diligence period; submitted together with mark-ups of the draft merger agreement and voting agreement.",
  why="Stated: “" + Q["d"] + "” and “" + Q["lois"] + "” (p.30). Formality: Formal — bidder-returned markups (signal 1). Conditions: Heavy — stated four-week substantive diligence period.",
  source=["P-019", "P-015"], review="Q5; Q7", count=1,
  dfrom="2016-07-20", dto="2016-07-27", wdate="2016-07-20",
  dbasis="Approximate window", dmethod="Assigned: deadline",
  plow=21.00, phigh=21.00, pkind="Point", porigin="Stated", currency="USD",
  allcash="Not stated", formality="Formal", cond="Heavy",
  cdetail="Fin: not stated; DD required: substantive (4 wks); DD open: yes; Excl: not stated", page=30),

R(rowid="R032", n=32, when="Late July 2016 (day not disclosed; before the 07/27/2016 selection)",
  who="Party C", what="Bid", rnd="2", type="Strategic",
  terms="LOI at $19.30 per share, subject to a 30-day diligence period. Follows Party C's 07/12/2016 IOI (R027).",
  why="Stated: “" + Q["c"] + "” (p.30). Formality: Informal — no returned agreement markup or final-solicitation response; the issues summary was Party E's. Conditions: Heavy — stated 30-day substantive diligence period.",
  source=["P-020"], review="Q5; Q7", count=0,
  dfrom="2016-07-20", dto="2016-07-27", wdate="2016-07-20",
  dbasis="Approximate window", dmethod="Assigned: deadline",
  plow=19.30, phigh=19.30, pkind="Point", porigin="Stated", currency="USD",
  allcash="Not stated", formality="Informal", cond="Heavy",
  cdetail="Fin: not stated; DD required: substantive (30 days); DD open: yes; Excl: not stated", page=30,
  related="same bidder as R027 in the same round; Count 0"),

R(rowid="R033", n=33, when="Late July 2016 (day not disclosed; before the 07/27/2016 selection)",
  who="Party F", what="Bid", rnd="2", type="Strategic",
  terms="LOI at $19.20 per share, subject to a 30-day due diligence period.",
  why="Stated: “" + Q["f"] + "” (p.30). Formality: Informal — no formal signal reported. Conditions: Heavy — stated 30-day substantive diligence period. Party F later supplies financing support to Party E's revised LOI (R046).",
  source=["P-021"], review="Q5; Q7", count=1,
  dfrom="2016-07-20", dto="2016-07-27", wdate="2016-07-20",
  dbasis="Approximate window", dmethod="Assigned: deadline",
  plow=19.20, phigh=19.20, pkind="Point", porigin="Stated", currency="USD",
  allcash="Not stated", formality="Informal", cond="Heavy",
  cdetail="Fin: not stated; DD required: substantive (30 days); DD open: yes; Excl: not stated", page=30,
  related="financing supporter of R046"),

R(rowid="R034", n=34, when="by 07/20/2016 (election day not disclosed)",
  who="One strategic buyer (anonymous)", what="Did not submit", rnd="2", type="Strategic",
  terms="Elected not to submit an LOI in the R2 solicitation; one of the two electors (one strategic, one financial) reported by the filing. No reason stated. Outcome stated, not inferred.",
  why="Stated: “" + Q["elect"] + "” (p.30). Assigned to the advancing group (the seven selected in R020) — the reading most consistent with the process narrative; unresolved base question in Q3. Working date = the LOI due date (Assigned: deadline).",
  source=["P-022"], review="Q3; Q4", count=1,
  dto="2016-07-20", wdate="2016-07-20",
  dbasis="Relative only", dmethod="Assigned: deadline", page=30,
  decided="Bidder", exit="Not stated", obasis="Stated"),

R(rowid="R035", n=35, when="by 07/20/2016 (election day not disclosed)",
  who="One financial buyer (anonymous)", what="Did not submit", rnd="2", type="Financial",
  terms="Elected not to submit an LOI in the R2 solicitation; the second elector. No reason stated. Outcome stated, not inferred.",
  why="Stated: “" + Q["elect"] + "” (p.30). Same base assumption as R034 (Q3). Working date = the LOI due date (Assigned: deadline).",
  source=["P-022"], review="Q3; Q4", count=1,
  dto="2016-07-20", wdate="2016-07-20",
  dbasis="Relative only", dmethod="Assigned: deadline", page=30,
  decided="Bidder", exit="Not stated", obasis="Stated"),

R(rowid="R036", n=36, when="07/21/2016", who="G&W", what="Bid", rnd="2", type="Strategic",
  terms="LOI at $21.15 per share: $20.02 cash at closing plus $1.13 in the form of a contingent value right (CVR) based on the subsequent sale of the South Quay property; subject to a three-week exclusive diligence period. Submitted mark-ups of the merger agreement and voting agreement and a disclosure-letter mark-up. Arrived after the 07/20/2016 due date and was considered (R028).",
  why="Stated: “" + Q["gw1"] + "” (p.29) and “" + Q["lois"] + "” (p.29). Formality: Formal — bidder-returned markups (signal 1). Conditions: Heavy — stated three-week exclusive diligence period. All cash Yes (the CVR is a contingent cash payment based on a property sale), fixed cash at closing $20.02 (Q6).",
  source=["P-015", "P-017"], review="Q5; Q6", count=1,
  dfrom="2016-07-21", dto="2016-07-21", wdate="2016-07-21",
  dbasis="Reported day", dmethod="Reported",
  plow=21.15, phigh=21.15, pkind="Point", porigin="Stated", currency="USD",
  allcash="Yes", cashclose=20.02, formality="Formal", cond="Heavy",
  cdetail="Fin: not stated; DD required: substantive (3 wks); DD open: yes; Excl: requested (3 wks)", page=29,
  related="revised by R037"),

R(rowid="R037", n=37, when="07/26/2016", who="G&W", what="Bid", rnd="2", type="Strategic",
  terms="Revised LOI at $22.15 per share: $21.02 cash at closing plus $1.13 CVR, after GHF feedback that the price and CVR structure were not competitive.",
  why="Stated: “" + Q["gw2"] + "” (p.29). Formality: Formal — carried forward from R036 (continuing proposal; no return to a preliminary basis). Conditions: Heavy — three-week exclusive diligence period persists; reconsidered at this revision. Count 0: same bidder, same round as R036.",
  source=["P-017"], review="Q5; Q6", count=0,
  dfrom="2016-07-26", dto="2016-07-26", wdate="2016-07-26",
  dbasis="Reported day", dmethod="Reported",
  plow=22.15, phigh=22.15, pkind="Point", porigin="Stated", currency="USD",
  allcash="Yes", cashclose=21.02, formality="Formal", cond="Heavy",
  cdetail="Fin: not stated; DD required: substantive (3 wks); DD open: yes; Excl: requested (3 wks)", page=29,
  related="revises R036; Count 0 (same bidder and round as R036)"),

R(rowid="R038", n=38, when="07/27/2016", who="Transaction Committee", what="Round opened", rnd="3",
  terms="R3 opens: after reviewing the LOIs (07/22/2016 telephone conference and 07/27/2016 in-person meeting), the committee chose G&W and Party B for confirmatory due diligence and negotiations because of their higher offers; remaining bidders were told they were no longer involved. Objective: on-site confirmatory diligence (07/27-08/11/2016) and negotiation of a definitive merger agreement with the two finalists. Finality: Inferred final — no announcement, but the target moved to definitive negotiation with selected bidders and to completing an agreement with one of them.",
  why="Stated: “" + Q["sel"] + "” (p.30) and “" + Q["onsite"] + "” (p.31). Convention: definitive negotiation with selected bidders opens R3 (section 6.3). Director Smith (GATX, 4.92% holder) recused himself from the process. Finality inferred from the move to definitive negotiation (Q1).",
  source=["P-023", "P-026"], review="Q1", rfinal="Inferred final",
  dfrom="2016-07-27", dto="2016-07-27", wdate="2016-07-27",
  dbasis="Reported day", dmethod="Reported", page=30,
  related="admits R043-R046; ends R2"),

R(rowid="R039", n=39, when="07/27/2016", who="Party E", what="Dropped by target", rnd="2",
  type="Strategic",
  terms="Told it was no longer involved after G&W and Party B were selected on higher offers. Stage left: Round 2 (finalist selection). Stated reason: lower offer than rivals (target choice).",
  why="Stated: “" + Q["sel"] + "” (p.30). Notification undated; Working date = the decision day (Assigned: decision day). Re-entry follows at R045.",
  source=["P-023"], count=1,
  dfrom="2016-07-27", dto="2016-07-27", wdate="2016-07-27",
  dbasis="Relative only", dmethod="Assigned: decision day", page=30,
  decided="Target", exit="Lower offer than rivals", obasis="Stated",
  related="re-enters at R045"),

R(rowid="R040", n=40, when="07/27/2016", who="Party D", what="Dropped by target", rnd="2",
  type="Financial",
  terms="Told it was no longer involved after G&W and Party B were selected on higher offers. Stage left: Round 2 (finalist selection). Stated reason: lower offer than rivals (target choice).",
  why="Stated: “" + Q["sel"] + "” (p.30). Notification undated; Working date = the decision day (Assigned: decision day). Re-entry follows at R043.",
  source=["P-023"], count=1,
  dfrom="2016-07-27", dto="2016-07-27", wdate="2016-07-27",
  dbasis="Relative only", dmethod="Assigned: decision day", page=30,
  decided="Target", exit="Lower offer than rivals", obasis="Stated",
  related="re-enters at R043"),

R(rowid="R041", n=41, when="07/27/2016", who="Party C", what="Dropped by target", rnd="2",
  type="Strategic",
  terms="Told it was no longer involved after G&W and Party B were selected on higher offers. Stage left: Round 2 (finalist selection); last participation was its $19.30 LOI (R032).",
  why="Stated: “" + Q["sel"] + "” (p.30). Notification undated; Working date = the decision day (Assigned: decision day).",
  source=["P-023"], count=1,
  dfrom="2016-07-27", dto="2016-07-27", wdate="2016-07-27",
  dbasis="Relative only", dmethod="Assigned: decision day", page=30,
  decided="Target", exit="Lower offer than rivals", obasis="Stated"),

R(rowid="R042", n=42, when="07/27/2016", who="Party F", what="Dropped by target", rnd="2",
  type="Strategic",
  terms="Told it was no longer involved after G&W and Party B were selected on higher offers. Stage left: Round 2 (finalist selection); its $19.20 LOI (R033) ends here. It later provides financing support to Party E's revised LOI (R046) without re-entering as an independent bidder.",
  why="Stated: “" + Q["sel"] + "” (p.30). Notification undated; Working date = the decision day (Assigned: decision day). Support recorded on R046; no new row for an exited supporter.",
  source=["P-023"], count=1,
  dfrom="2016-07-27", dto="2016-07-27", wdate="2016-07-27",
  dbasis="Relative only", dmethod="Assigned: decision day", page=30,
  decided="Target", exit="Lower offer than rivals", obasis="Stated"),

R(rowid="R043", n=43, when="08/01/2016", who="Party D", what="Re-entered", rnd="3",
  type="Financial",
  terms="Renewed participation after being told it was out on 07/27/2016: in the 07/29/2016 calls Party D expressed interest in reengaging and enhancing its offer and it submitted a revised LOI on 08/01/2016.",
  why="Stated: “" + Q["calls"] + "” (p.30) and “" + Q["rev"] + "” (p.30). Re-entered requires renewed activity, not formal admission; the revised LOI considered by the committee on 08/01/2016 supplies it.",
  source=["P-024"], review="Q4", count=1,
  dfrom="2016-08-01", dto="2016-08-01", wdate="2016-08-01",
  dbasis="Reported day", dmethod="Reported", page=30,
  related="after R040; before R044"),

R(rowid="R044", n=44, when="08/01/2016", who="Party D", what="Bid", rnd="3", type="Financial",
  terms="Revised LOI at $24.00 per share, subject to a 30-day due diligence period. On 08/02/2016 Party D also requested a Company commitment not to sign with another bidder during that period.",
  why="Stated: “" + Q["rev"] + "” and “" + Q["dout"] + "” (p.30). Formality: Formal — carried forward from R031 (continuing proposal). Conditions: Heavy — stated 30-day substantive diligence; Excl records the requested no-sign commitment (30 days), which was not granted (R048).",
  source=["P-024"], review="Q5; Q6", count=1,
  dfrom="2016-08-01", dto="2016-08-01", wdate="2016-08-01",
  dbasis="Reported day", dmethod="Reported",
  plow=24.00, phigh=24.00, pkind="Point", porigin="Stated", currency="USD",
  allcash="Not stated", formality="Formal", cond="Heavy",
  cdetail="Fin: not stated; DD required: substantive (30 days); DD open: no; Excl: requested (30 days)", page=30,
  related="revises R031; closed at R048"),

R(rowid="R045", n=45, when="08/01/2016", who="Party E", what="Re-entered", rnd="3",
  type="Strategic",
  terms="Renewed participation after being told it was out on 07/27/2016: in the 07/29/2016 calls Party E expressed interest in reengaging and enhancing its offer and it submitted a revised LOI on 08/01/2016.",
  why="Stated: “" + Q["calls"] + "” (p.30) and “" + Q["rev"] + "” (p.30). The revised LOI considered by the committee on 08/01/2016 establishes renewed activity.",
  source=["P-024"], review="Q4", count=1,
  dfrom="2016-08-01", dto="2016-08-01", wdate="2016-08-01",
  dbasis="Reported day", dmethod="Reported", page=30,
  related="after R039; before R046"),

R(rowid="R046", n=46, when="08/01/2016", who="Party E", what="Bid", rnd="3", type="Strategic",
  terms="Support: Party F (financing) — revised LOI at $23.81 per share, submitted with financing support from Party F (which submitted its own $19.20 LOI in R2 and exited on 07/27/2016); subject to a 30-day due diligence period. Party F is a financing supporter, not a member of a bidding group.",
  why="Stated: “" + Q["rev"] + "” (p.30). Formality: Informal — the original LOI was an issues summary and no new formal signal (markup) is reported (Q5). Conditions: Heavy — stated 30-day substantive diligence. Financing support recorded here; exited supporter gets no new row (section 5.3).",
  source=["P-024"], review="Q5; Q6", count=1,
  dfrom="2016-08-01", dto="2016-08-01", wdate="2016-08-01",
  dbasis="Reported day", dmethod="Reported",
  plow=23.81, phigh=23.81, pkind="Point", porigin="Stated", currency="USD",
  allcash="Not stated", formality="Informal", cond="Heavy",
  cdetail="Fin: represented; DD required: substantive (30 days); DD open: yes; Excl: not stated", page=30,
  related="revises R030; Support: R033 (Party F, financing)"),

R(rowid="R047", n=47, when="08/02/2016", who="Party E", what="Bid reaffirmed", rnd="3",
  type="Strategic",
  terms="Bid reversion: withdrew its 08/01/2016 revised $23.81 proposal but confirmed its original $21.26 proposal, whose conditions (60-day exclusivity for diligence and definitive documentation) stand. Not a process withdrawal.",
  why="Stated: “" + Q["ewd"] + "” (p.30). Price carried forward from R030 (identified earlier row; not a new price observation). Formality: Informal — never established as Formal. Conditions: Heavy — the original LOI's stated 60-day exclusive diligence period carries with the confirmed proposal; DD open not disclosed for this date.",
  source=["P-024"], review="Q4; Q5", count=0,
  dfrom="2016-08-02", dto="2016-08-02", wdate="2016-08-02",
  dbasis="Reported day", dmethod="Reported",
  plow=21.26, phigh=21.26, pkind="Point", porigin="Carried forward", currency="USD",
  allcash="Not stated", formality="Informal", cond="Heavy",
  cdetail="Fin: not stated; DD required: substantive (60 days); DD open: not disclosed; Excl: requested (60 days)", page=30,
  related="reverts to R030; withdraws R046; Count 0 (same bidder and round as R046)"),

R(rowid="R048", n=48, when="08/02/2016", who="Party D", what="Withdrew", rnd="3",
  type="Financial",
  terms="Declined to shorten its 30-day diligence and requested a commitment that the Company not sign with another bidder during that period; the Company declined (active interest of Party B and G&W); Party D then indicated it would not proceed with further diligence at that time. Stage left: Round 3.",
  why="Stated: “" + Q["dout"] + "” (p.30). Bidder-side decision not to continue; read as a withdrawal (Bidder), not a temporary pause, though the filing says 'at that time' (alternative flagged, Q4). Exit reason Terms or process: the unavailable no-sign commitment, not price.",
  source=["P-024"], review="Q4", count=1,
  dfrom="2016-08-02", dto="2016-08-02", wdate="2016-08-02",
  dbasis="Reported day", dmethod="Reported", page=30,
  decided="Bidder", exit="Terms or process", obasis="Stated",
  related="closes R044"),

R(rowid="R049", n=49, when="08/04/2016", who="Party B", what="Bid reaffirmed", rnd="3",
  type="Strategic",
  terms="Reaffirmed by: returned draft — Party B's legal counsel returned a revised merger-agreement draft while the Company was finalizing an agreement with Party B (committee direction 08/04/2016 to prioritize and complete negotiation with Party B); $24.00 carried forward from R029. On-site diligence continued to 08/11/2016. Flagged for review (late reconfirmation).",
  why="Stated: “" + Q["baug4"] + "” (p.31), “" + Q["prior"] + "” (p.31) and “" + Q["onsite"] + "” (p.31). Conditions: Light — the only condition Party B attached was an expedited diligence review; DD open: yes (on-site through 08/11/2016). A returned draft does not itself show diligence or financing conditions have fallen away; the price is not restated as a new observation (Q5).",
  source=["P-026", "P-027"], review="Q5", count=1,
  dfrom="2016-08-04", dto="2016-08-04", wdate="2016-08-04",
  dbasis="Reported day", dmethod="Reported",
  plow=24.00, phigh=24.00, pkind="Point", porigin="Carried forward", currency="USD",
  allcash="Not stated", formality="Formal", cond="Light",
  cdetail="Fin: not stated; DD required: confirmatory; DD open: yes; Excl: not stated", page=31,
  related="reaffirms R029"),

R(rowid="R050", n=50, when="08/09/2016", who="Transaction Committee", what="Target decision", rnd="3",
  terms="Committee directed BMO to tell G&W the Company intended to enter into a merger agreement with another bidder (Party B); G&W asked to continue diligence on 08/10-08/11/2016 to potentially facilitate an improved offer, which was granted.",
  why="Stated: “" + Q["gwsept"] + "” (p.31). Preferred-bidder decision; continuing diligence for G&W was allowed and produced the 08/12/2016 revised LOI (R053).",
  source=["P-027"], count=None,
  dfrom="2016-08-09", dto="2016-08-09", wdate="2016-08-09",
  dbasis="Reported day", dmethod="Reported", page=31,
  related="leads to R053"),

R(rowid="R051", n=51, when="Service first observed 08/10/2016 (retention date not disclosed)",
  who="Simpson Thacher & Bartlett LLP (G&W legal counsel)", what="Adviser service observed", rnd="3",
  terms="G&W's legal counsel; negotiated merger-agreement and disclosure-letter provisions with Hinckley Allen and participated in finalizing documents through signing on 08/12/2016.",
  why="Stated: “" + Q["simpson"] + "” (p.31). Adviser service observed at the earliest supported service date; the filing does not disclose G&W's financial adviser (Summary).",
  source=["P-027"], count=None,
  dfrom="2016-08-10", dto="2016-08-10", wdate="2016-08-10",
  dbasis="Reported day", dmethod="Reported", page=31),

R(rowid="R052", n=52, when="08/12/2016 (call date; counsel unnamed)",
  who="Unnamed STB counsel (Company)", what="Adviser service observed", rnd="3",
  terms="Regulatory counsel; advised the Board during the 08/12/2016 meeting on STB approval paths, voting-trust use and timing for a transaction with either finalist.",
  why="Stated: “" + Q["stb"] + "” (p.32). The filing does not name the firm; recorded generically as the Company's STB counsel (an unnamed firm is not inferred to be a later-named adviser).",
  source=["P-031"], count=None,
  dfrom="2016-08-12", dto="2016-08-12", wdate="2016-08-12",
  dbasis="Reported day", dmethod="Reported", page=32),

R(rowid="R053", n=53, when="08/12/2016", who="G&W", what="Bid", rnd="3", type="Strategic",
  terms="Revised LOI at $25.00 per share in cash, excluding the earlier CVR, with mark-ups of the merger agreement and voting agreement (disclosure-letter mark-up followed the same day); offer to expire at 6:00 p.m. on 08/13/2016. Signalled on 08/11/2016 after completing physical diligence.",
  why="Stated: “" + Q["gw25"] + "” (p.31) and “" + Q["gwsignal"] + "” (p.31). Formality: Formal — returned agreement markups (signal 1). Conditions: Light — diligence completed (DD open: no), documents still being negotiated to signing; no financing condition in the executed agreement and G&W represented its financial wherewithal (X-015). All cash Yes; $25.00 fixed at closing; CVR removed. Alternative None reading flagged (Q5, Q6).",
  source=["P-027", "P-028", "X-015"], review="Q5; Q6", count=1,
  dfrom="2016-08-12", dto="2016-08-12", wdate="2016-08-12",
  dbasis="Reported day", dmethod="Reported",
  plow=25.00, phigh=25.00, pkind="Point", porigin="Stated", currency="USD",
  allcash="Yes", cashclose=25.00, formality="Formal", cond="Light",
  cdetail="Fin: no contingency; DD required: none; DD open: no; Excl: not stated", page=31,
  related="revises R037; accepted at R056"),

R(rowid="R054", n=54, when="08/12/2016", who="Party B", what="Not selected at signing", rnd="3",
  type="Strategic",
  terms="Still-live finalist: asked by BMO (at the Board's request) whether it would increase its price and it declined; the Board then determined the G&W offer was the superior proposal and signed with G&W. Diligence had ended 08/11/2016. Stage left: Round 3.",
  why="Stated: “" + Q["bdecline"] + "” (p.32) and “" + Q["superior"] + "” (p.32). Outcome basis Stated (the bidder was still bidding when the target chose another). Exit reason Would not improve earlier offer, while actual selection agency is the target's.",
  source=["P-031", "P-032"], review="Q4", count=1,
  dfrom="2016-08-12", dto="2016-08-12", wdate="2016-08-12",
  dbasis="Reported day", dmethod="Reported", page=32,
  decided="Target", exit="Would not improve earlier offer", obasis="Stated",
  related="after R049"),

R(rowid="R055", n=55, when="by 08/12/2016", who="Party E", what="Not selected at signing", rnd="3",
  type="Strategic",
  terms="Inferred: silent — last reported act was confirming its original $21.26 proposal on 08/02/2016 (R047) after withdrawing its revised proposal; never mentioned again before signing. Stage left: Round 3.",
  why="Inferred: “" + Q["ewd"] + "” (p.30) is its last appearance; no notice of exclusion or withdrawal after it is reported. The row records only that Party E was out by signing, not how or why (Q4).",
  source=["P-024", "P-033"], review="Q4", count=1,
  dto="2016-08-12", wdate="2016-08-12",
  dbasis="Relative only", dmethod="Assigned: bound", page=30,
  decided="Unknown", exit="Not stated", obasis="Inferred: silent"),

R(rowid="R056", n=56, when="08/12/2016", who="PWRR and G&W (with Merger Sub)",
  what="Merger agreement signed", rnd="3",
  terms="Agreed consideration $25.00 per share in cash (preferred converts 100-for-1 plus accrued/unpaid dividends); Board approval (Director Smith recused) after BMO's oral fairness opinion of the same date; Eder Trusts (842,742 common; 500 preferred) executed a voting agreement with G&W and the Company; termination fee $3,785,000; no go-shop; outside date 12/31/2016 (02/28/2017 if only STB approval remains). Signing is not process termination and is not a new bid.",
  why="Stated: “" + Q["exec"] + "” (p.32), “" + Q["opinion"] + "” (p.32), “" + Q["superior"] + "” (p.32) and “" + Q["fee3785"] + "” (p.34); G&W draft terms favored the winner: “" + Q["gwx"] + "” (p.32). Routine approval/opinion details incorporated here. No go-shop or post-signing competing proposal is reported in the supplied filing.",
  source=["P-032", "P-033", "X-014", "X-016", "X-026"], count=None,
  dfrom="2016-08-12", dto="2016-08-12", wdate="2016-08-12",
  dbasis="Reported day", dmethod="Reported", page=32,
  related="R053 (accepted); R054; R049; voting agreement noted"),

R(rowid="R057", n=57, when="08/15/2016", who="PWRR", what="Merger announced", rnd="3",
  terms="Press release publicly announced the transaction on Monday 08/15/2016 before the opening of trading of the common stock on NASDAQ. Separate from signing (08/12/2016).",
  why="Stated: “" + Q["ann"] + "” (p.32). Publicity occurred after signing; no earlier sale-process announcement is reported.",
  source=["P-033"], count=None,
  dfrom="2016-08-15", dto="2016-08-15", wdate="2016-08-15",
  dbasis="Reported day", dmethod="Reported", page=32),
]
